# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):

    obj = bld.create_ns3_program('runner', ['grail'])
    obj.source = 'runner.cc'


    obj = bld.create_ns3_program('runner-2', ['grail'])
    obj.source = 'runner-2.cc'
